name: model-training
on:
  push: {}

permissions:
  issues: write
  contents: write
  pull-requests: write
  
jobs:
  model_training_job:
    name: Examople Training Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: CML
        uses: iterative/setup-cml@v1
          
      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          pip install --upgrade pip
          python train.py

          npm install -g @dvcorg/cml
          echo "## Metrics" > data.md
          cat metrics.txt >> data.md
          
          echo "## Plots" >> data.md
          echo '![](./feature_importance.png "feature importance")' >> data.md
          echo '![](./residuals.png "residuals")' >> data.md

          cml comment create data.md

